const CATS = [
  {id:"tests", name:"Health tests", blurb:"Doctor vs Disease: blood, urine and scan tests explained as a fight."},
  {id:"preg", name:"Pregnancy care", blurb:"A three-part series for mothers-to-be."},
  {id:"gen", name:"Genetic tests", blurb:"Karyotype, microarray and exome: finding the cause in the genes."},
  {id:"bio", name:"Biology made simple", blurb:"From one protein to the whole body."},
  {id:"daily", name:"Daily health tips", blurb:"Seasonal tips posted on the page."}
];

const V = [
 {id:"lft", c:"tests", t:"Liver Function Test (LFT)", l:"Hindi", d:"2:21",
  s:"Dr. Health fights Fatty Liver, Hepatitis and Alcohol with the LFT blood test.",
  x:[["What it checks","SGPT and SGOT (liver damage alarm), bilirubin (jaundice), albumin (liver strength), ALP (bile flow)."],
     ["Who should test","People who drink alcohol regularly, are overweight or diabetic, take long-term medicines, or have had jaundice or hepatitis."],
     ["Approximate normal","SGPT/SGOT up to about 40 U/L · Bilirubin 0.3–1.2 mg/dL · Albumin 3.5–5.0 g/dL"],
     ["Good to know","Early fatty liver can often be reversed with diet and exercise. Your liver can regrow itself."]]},
 {id:"lipid", c:"tests", t:"Lipid Profile", l:"Hindi", d:"2:16",
  s:"Your heart against Bad Cholesterol, Smoking and Junk Food. High cholesterol has no symptoms.",
  x:[["What it checks","Total cholesterol, LDL (bad), HDL (good) and triglycerides."],
     ["Who should test","Every adult from age 20, yearly after 40; people with diabetes, high BP, smoking, extra weight, or early heart attack in the family."],
     ["Preparation","Fast for 10–12 hours. Water is fine. Follow your lab's instructions."],
     ["Healthy levels (mg/dL)","Total below 200 · LDL below 100 · Triglycerides below 150 · HDL above 40 (men) / 50 (women)"]]},
 {id:"cbc", c:"tests", t:"CBC (Complete Blood Count)", l:"Hindi", d:"2:21",
  s:"The blood team of red cells, white cells and platelets fights Anaemia, Infection and Dengue.",
  x:[["What it checks","Haemoglobin and RBC (anaemia), WBC (infection), platelets (dengue and bleeding)."],
     ["Who should test","Tiredness or pale skin, fever for 2 days or more, pregnancy, and a yearly check-up."],
     ["Preparation","No fasting needed."],
     ["Approximate normal","Hb men 13–17 / women 12–15 g/dL · WBC 4,000–11,000 /cumm · Platelets 1.5–4.5 lakh /cumm"]]},
 {id:"kft", c:"tests", t:"Kidney Function Test (KFT)", l:"Hindi", d:"2:25",
  s:"Kidneys can fail silently. The kidney hero takes on Diabetes, High BP and painkiller overuse.",
  x:[["What it checks","Creatinine (filter alarm), urea (waste level), eGFR (filter speed), uric acid and salts."],
     ["Who should test","Diabetes or high BP, long-term painkiller use, swelling in feet or face, foamy urine, kidney disease in the family."],
     ["Approximate normal","Creatinine men 0.7–1.3 / women 0.6–1.1 mg/dL · Urea 15–40 mg/dL · eGFR 90 or above"],
     ["Good to know","Usually no fasting needed. Never take painkillers without a doctor's advice."]]},
 {id:"usg", c:"tests", t:"Whole Abdomen USG", l:"Hindi", d:"2:32",
  s:"An ultrasound uses sound waves to find Gallstones, Fatty Liver and Kidney Stones. No radiation, no pain.",
  x:[["What it shows","Liver and gallbladder, kidneys and bladder, pancreas and spleen, uterus and ovaries or prostate."],
     ["Preparation","Fast 6–8 hours. Drink 4–5 glasses of water an hour before and hold urine so the bladder stays full."],
     ["Report words","Calculus = stone · Cholelithiasis = gallbladder stones · Hepatomegaly = enlarged liver · Simple cyst = fluid bubble, often harmless"],
     ["Good to know","Painless, safe in pregnancy, and usually takes 15–20 minutes."]]},
 {id:"echo", c:"tests", t:"2D Echo (Echocardiography)", l:"Hindi", d:"2:37",
  s:"An ultrasound of the heart that checks its size, pumping power and valves.",
  x:[["What it shows","Heart size and wall thickness, pumping power (EF), valves (open, close or leak), holes and fluid around the heart."],
     ["When it's advised","Breathlessness, chest pain, swelling in the feet, a heart murmur, or long-standing high BP or diabetes."],
     ["Report words","EF 55–70% = normal pumping · LVH = thick heart wall · MR/TR/AR = leaky valve · Stenosis = narrow valve"],
     ["ECG vs Echo","ECG checks the heart's electrical rhythm. Echo shows moving pictures of its structure."]]},
 {id:"urine", c:"tests", t:"Urine Routine (R/E)", l:"Hindi", d:"2:25",
  s:"A small sample with a big report card, plus the urine colour chart.",
  x:[["What it checks","Colour and clarity, sugar and protein, pus cells and bacteria (infection), blood and crystals (stone clues)."],
     ["How to give the sample","First morning urine, clean the area, skip the first few drops, use the lab's sterile cup, and deliver within an hour."],
     ["Usually normal","Sugar nil · Protein nil or trace · Pus cells 0–5 /hpf · RBC 0–2 /hpf"],
     ["Colour guide","Pale yellow = well hydrated · Dark yellow = drink more water · Red or brown = see a doctor"]]},
 {id:"culture", c:"tests", t:"Urine Culture & Sensitivity", l:"Hindi", d:"2:35",
  s:"Finds the exact germ behind a UTI and which antibiotic will actually work.",
  x:[["What it does","Grows germs from urine on a lab plate for 48–72 hours, then tests antibiotics against them."],
     ["When it's advised","Repeated UTI, no improvement with medicine, fever with burning urine, pregnancy, children and catheter patients."],
     ["Report words","No growth = usually no infection · More than 1 lakh CFU/mL = significant · S = antibiotic works · R = it won't"],
     ["Most important tip","Give the sample before starting antibiotics. Never take antibiotics without a doctor."]]},
 {id:"hba1c", c:"tests", t:"HbA1c & Blood Sugar", l:"Bengali", d:"2:08",
  s:"Why your doctor asks for HbA1c even when the sugar test is normal.",
  x:[["What it checks","Your average blood sugar over the last 2–3 months."],
     ["Who should test","Everyone above 30 yearly; family history of diabetes, extra weight, high BP or PCOS; diabetics every 3 months."],
     ["Results","HbA1c below 5.7% normal · 5.7–6.4% prediabetes · 6.5% or above diabetes"],
     ["Good to know","No fasting needed for HbA1c. Anaemia or thalassaemia can make it misleading."]]},
 {id:"vitd", c:"tests", t:"Vitamin D & B12", l:"Bengali", d:"2:13",
  s:"Always tired, aching or tingling? It could be low Vitamin D or B12.",
  x:[["What it checks","Vitamin D for bones and muscles; Vitamin B12 for blood and nerves."],
     ["Who should test","People mostly indoors, women over 40 and the elderly, vegetarians, and long-term metformin or acidity-tablet users."],
     ["Approximate normal","Vitamin D 30–100 ng/mL · B12 above 300 pg/mL"],
     ["Good to know","Don't take high-dose Vitamin D on your own. Test first."]]},

 {id:"dmarker", c:"preg", t:"Double Marker Test", l:"Hindi", d:"2:11",
  s:"Part 1. A first-trimester blood test, and what 'high risk' really means.",
  x:[["What it is","A blood test (beta-hCG and PAPP-A) read together with the NT scan."],
     ["When","Between 11 and 14 weeks of pregnancy. If missed, triple or quad marker at 15–20 weeks."],
     ["What it screens for","The chance of Down syndrome (21), Edwards (18) and Patau (13)."],
     ["Remember","Screening is not diagnosis. Most high-risk results still have healthy babies. Baby's sex is never disclosed."]]},
 {id:"nipt", c:"preg", t:"NIPT", l:"Hindi", d:"2:26",
  s:"Part 2. Reads tiny pieces of the baby's DNA in the mother's blood.",
  x:[["What it is","Non-Invasive Prenatal Test: one blood sample from the mother. Safe for the baby."],
     ["When","From 10 weeks of pregnancy. Results usually in 1–2 weeks."],
     ["Accuracy","Detects over 99% of Down syndrome cases, but it is still a screening test."],
     ["Good to know","An anomaly scan is still needed. Costlier than double marker. Tell your doctor about twins or IVF."]]},
 {id:"cvs", c:"preg", t:"CVS & Amniocentesis", l:"Hindi", d:"2:29",
  s:"Part 3. Diagnostic tests that give a confirmed answer.",
  x:[["CVS","At 11–14 weeks. A tiny sample of placenta, taken under ultrasound."],
     ["Amniocentesis","From 15 weeks. 3–4 teaspoons of the fluid around the baby."],
     ["What they confirm","Chromosome conditions, thalassaemia major in the baby, and other genetic diseases."],
     ["Safety","Done by an expert in a few minutes. Small miscarriage risk, usually under 1%. Rh-negative mothers may need anti-D."]]},

 {id:"karyo", c:"gen", t:"Karyotyping", l:"Hindi", d:"2:42",
  s:"Counts all 46 chromosomes. Key test for repeated miscarriages and infertility.",
  x:[["What it checks","All 46 chromosomes (23 pairs): extra or missing chromosomes and swapped pieces (translocations)."],
     ["Who should test","Couples with 2 or more miscarriages, infertility or very low sperm count, a child with delay or birth defects, girls with short height and no periods, some blood cancers (bone marrow)."],
     ["Sample & time","Usually a blood sample; in pregnancy, a CVS or amniocentesis sample. Report in about 2–3 weeks."],
     ["Reading the report","46,XX = normal female · 46,XY = normal male · 47,XY,+21 = Down syndrome. The first number is the total count."],
     ["Good to know","Very small changes are missed; microarray or exome may be needed. Baby's sex is not disclosed in pregnancy."]]},
 {id:"cma", c:"gen", t:"Chromosomal Microarray: 750K vs 315K", l:"Hindi", d:"2:51",
  s:"Finds tiny missing or extra chromosome pieces that a karyotype cannot see.",
  x:[["What it checks","Small deletions (missing pieces) and duplications (extra pieces) across all chromosomes."],
     ["750K vs 315K","750K: about 7.5 lakh probes, finer detail, mostly for children and adults. 315K: about 3.15 lakh probes, focused on key regions, mostly for pregnancy (CVS/amnio) and miscarriage tissue."],
     ["Who should test","Developmental delay, autism, birth defects, a problem seen on the baby's scan, repeated miscarriage or stillbirth."],
     ["Why it matters","Finds a cause in about 15–20% of children with delay or autism, versus about 3–5% with karyotype."],
     ["Good to know","Does not show balanced translocations (karyotype) or single-letter changes (exome). Parents' samples may be needed."]]},
 {id:"wes", c:"gen", t:"Whole Exome Sequencing", l:"Hindi", d:"2:40",
  s:"Reads about 20,000 genes letter by letter when other tests give no answer.",
  x:[["What it checks","The exome: the 1–2% of DNA that holds the recipes for proteins, where most known disease-causing changes are found."],
     ["Who should test","Delayed development, unexplained fits or muscle weakness, multiple birth defects, unknown genetic illness in the family, or when other tests gave no answer."],
     ["Sample & time","Blood (or saliva). Report in about 3–6 weeks. Testing the child with both parents ('trio') gives more reliable results."],
     ["Reading the report","Positive (cause found) · Negative (no cause found, genetic not ruled out) · VUS (change of uncertain meaning). About 1 in 3 families find an answer."],
     ["Good to know","Cannot catch every change (e.g. Fragile X). Genetic counselling before and after is important."]]},

 {id:"story", c:"bio", t:"From Protein to Cell: the full story", l:"Hindi", d:"4:09",
  s:"Seven chapters in one video: protein, gene, DNA, histones, chromosome, nucleus and cell.",
  x:[["Chapters","Protein · Gene · DNA · Histones · Chromosome · Nucleus · Cell"],
     ["Big picture","Recipes for proteins are in genes, genes are in DNA, DNA wraps into chromosomes inside the nucleus of every cell."],
     ["Lab link","Albumin (protein), HPLC (haemoglobin), karyotype (chromosomes), Pap smear (cells), CBC (blood cells)."]]},
 {id:"cell", c:"bio", t:"What is a Cell?", l:"Hindi", d:"2:03",
  s:"You are made of about 30 lakh crore cells. Each one is a tiny factory.",
  x:[["Parts","Membrane = security wall · Nucleus = head office · Mitochondria = powerhouse · Ribosomes = protein workers"],
     ["Lifespan","Skin cells 2–4 weeks · Red blood cells about 120 days · Many nerve cells a whole lifetime"],
     ["Lab link","CBC counts blood cells; Pap smear and FNAC look at cells under the microscope."]]},
 {id:"nucleus", c:"bio", t:"What is the Nucleus?", l:"Hindi", d:"1:44",
  s:"Every cell has a boss, except red blood cells.",
  x:[["Inside","A wall with gates (nuclear pores), DNA files, and the nucleolus."],
     ["Fun fact","Red blood cells have no nucleus, which leaves more room for haemoglobin."],
     ["Lab link","WBC types are told apart by nucleus shape (the CBC differential)."]]},
 {id:"chromosome", c:"bio", t:"What is a Chromosome?", l:"Hindi", d:"2:20",
  s:"46 chromosomes in 23 pairs, and the truth about who decides a baby's sex.",
  x:[["Basics","46 chromosomes in every cell: 23 from mother, 23 from father."],
     ["Myth busted","The father's X or Y decides whether a baby is a boy or girl, not the mother. Sex determination before birth is illegal in India."],
     ["Tests","Karyotyping; double marker or NIPT in pregnancy, as your doctor advises."]]},
 {id:"dna", c:"bio", t:"What is DNA?", l:"Hindi", d:"1:57",
  s:"A 4-letter code, about 3 billion letters long, in every cell.",
  x:[["The code","Four letters: A pairs with T, G pairs with C."],
     ["Fun fact","You share about 99.9% of your DNA with every human. DNA from one cell is about 2 metres long."],
     ["Tests","Genetic disease tests like thalassaemia, some cancer risk genes, paternity, and forensics."]]},
 {id:"gene", c:"bio", t:"What is a Gene?", l:"Hindi", d:"1:47",
  s:"DNA is the cookbook, a gene is one recipe, a protein is the dish.",
  x:[["Basics","About 20,000 genes, each in two copies: one from mother, one from father."],
     ["Carriers","Two healthy thalassaemia carriers have a 1 in 4 chance, each pregnancy, of a child with thalassaemia major."],
     ["Lifestyle","Family history raises risk, but healthy habits can change the story."]]},
 {id:"histones", c:"bio", t:"What are Histones?", l:"Hindi", d:"1:59",
  s:"Protein spools that pack 2 metres of DNA into a tiny cell and switch genes on and off.",
  x:[["Basics","Eight histones make one core. DNA wraps around it to form a nucleosome, like beads on a string."],
     ["Gene switch","Tight wrap = gene off; loose wrap = gene on. This is epigenetics."],
     ["Don't confuse","Histones are not antihistamines. Antihistamines are allergy medicines."]]},

 {id:"thyroid", c:"daily", t:"Thyroid test (TSH, T3, T4)", l:"Hindi", d:"2:24",
  s:"Wednesday tips, 7 Oct 2026. Always tired, weight going up, hair falling? Check your thyroid.",
  x:[["What it checks","TSH (the signal from the brain) and T3, T4 (the thyroid hormones). TSH high usually means a slow thyroid; TSH low usually means a fast thyroid."],
     ["Symptoms","Slow (hypo): tiredness, weight gain, feeling cold, hair fall, constipation. Fast (hyper): weight loss, fast heartbeat, sweating, shaky hands, anxiety."],
     ["Who should test","Women over 35, before or during pregnancy, after delivery, thyroid in the family, diabetes, PCOD or irregular periods. For newborns, ask your doctor about thyroid screening."],
     ["Preparation","Usually no fasting. Morning sample is best. On a thyroid tablet, give the sample before the dose as your doctor says. Tell your doctor if you take biotin."],
     ["Good to know","About 1 in 10 adults in India has hypothyroidism. Never stop or change your thyroid tablet on your own."]]},
 {id:"alz", c:"tests", t:"Alzheimer's & memory loss tests", l:"Hindi", d:"3:24",
  s:"Forgetting the way home? How doctors check for Alzheimer's, and which causes can be treated.",
  x:[["Is there one test?","No single test. Doctors (usually a neurologist or psychiatrist) combine memory tests such as MMSE, blood tests and a brain scan."],
     ["Warning signs","Forgetting recent events, asking the same question again, getting lost in familiar places, trouble with money or daily tasks, mood or behaviour changes."],
     ["Blood tests","Look for treatable causes: vitamin B12, thyroid, sugar, CBC (anaemia), kidney and liver tests. Treating these can improve memory."],
     ["Brain scan","MRI or CT rules out stroke, tumour or fluid and can show brain shrinkage. Sometimes PET or spinal fluid tests are used."],
     ["New blood test","pTau217 / Beta-Amyloid 1-42 ratio (plasma): a blood sample, report in about 48 hours, for adults 50+ with signs of memory decline. Positive = high chance of Alzheimer's-related amyloid changes; grey zone = more tests may be needed; negative = very low chance. Not a screening test and not a diagnosis on its own; your doctor reads it with other tests."],
     ["In India","About 7.4% of people over 60 (around 88 lakh) have dementia (LASI-DAD, 2023). Up to 45% of dementia may be prevented or delayed (Lancet Commission, 2024)."]]},
 {id:"uric", c:"daily", t:"Uric acid test: gout & joint pain", l:"Hindi", d:"3:04",
  s:"Saturday tips, 10 Oct 2026. Sudden pain and swelling in the big toe? What uric acid is, why it rises and how to read the test.",
  x:[["What it is","Uric acid is a waste made when purines (found in our cells and some foods) break down. Most of it leaves the body through the kidneys in urine."],
     ["Why it matters","If the body makes too much or the kidneys remove too little, the level rises. Needle-like crystals can form in joints (gout), and some people get kidney stones."],
     ["What can raise it","Red and organ meat, some seafood, alcohol (especially beer), sugary soft drinks, extra weight, kidney disease, some medicines, and gout in the family."],
     ["The test","A simple blood test; some labs ask for a few hours of fasting, so follow your lab's instructions. Avoid alcohol before the test and tell your doctor about your medicines. A 24-hour urine uric acid is sometimes done, mainly for kidney stones."],
     ["Reading the result","Usually about 3.5 to 7 mg/dL (approximately), a little lower in women; ranges vary by lab. Uric acid can be normal during a gout attack, and many people with high uric acid never get gout. Whether medicine is needed is decided by your doctor."]]},
 {id:"sugar", c:"daily", t:"Blood sugar: fasting, PP & GTT", l:"Hindi", d:"2:49",
  s:"Friday tips, 9 Oct 2026. Thirsty, passing urine often, slow healing? The 3 main sugar tests and what the numbers mean.",
  x:[["Fasting (FBS)","No food for at least 8 hours; plain water is fine. Below 100 mg/dL normal, 100–125 prediabetes, 126 or more may be diabetes (ADA criteria)."],
     ["PP (post-meal)","Blood taken 2 hours from the start of your usual meal. Usually below 140 mg/dL is considered normal; lab ranges vary slightly."],
     ["GTT (75 g)","Fasting sample, then 75 g glucose drink and a sample at 2 hours. Below 140 normal, 140–199 prediabetes, 200 or more diabetes. Don't eat and sit quietly during the test."],
     ["In pregnancy","India uses the DIPSI test: 75 g glucose, fasting not needed; 2-hour value of 140 mg/dL or more means gestational diabetes. First visit and again at 24–28 weeks."],
     ["Who should test","Everyone above 30, family history of diabetes, overweight or high BP, PCOD, or thirst, frequent urination and tiredness. Doctors confirm with a repeat test."]]},
 {id:"ecg", c:"daily", t:"ECG test: the heart tracing", l:"Hindi", d:"3:02",
  s:"Thursday tips, 8 Oct 2026. Chest pain, racing heart or dizziness? What an ECG shows and how to prepare.",
  x:[["What it is","An ECG (electrocardiogram) records the heart's tiny electrical signals as waves. Painless, takes only a few minutes, and no current goes into the body."],
     ["When doctors advise it","Chest pain or heaviness, fast or irregular heartbeat, dizziness or fainting, breathlessness, suspected heart attack. Also before an operation, after a past heart problem, with a strong family history of heart disease, or to check a pacemaker."],
     ["Preparation","Wear a top that opens easily. No cream, oil or powder on the chest. No exercise or cold water just before the test. Tell the staff about your medicines. Lie still and relax."],
     ["Reading the report","A resting heart rate of about 60 to 100 per minute with a regular rhythm is usually considered normal. An ECG records only a few seconds, so a normal ECG does not rule out every heart problem; your doctor may advise Holter, TMT or ECHO and reads the ECG with your symptoms."],
     ["Heart attack warning signs","Chest pain or pressure spreading to the arm, jaw or back, with sweating, breathlessness or uneasiness. Women, the elderly and people with diabetes may have no chest pain. Don't wait: call an ambulance or go to the nearest hospital."]]},
 {id:"fever", c:"daily", t:"Dengue, Malaria or Typhoid?", l:"Hindi", d:"1:49",
  s:"Monday tips, 5 Oct 2026. Same fever, different test.",
  x:[["Dengue","High fever, eye and body pain, rash. Test: NS1 (days 1–5), IgM (after day 5), CBC for platelets."],
     ["Malaria","Fever with chills that comes and goes. Test: rapid antigen test or blood smear."],
     ["Typhoid","Slowly rising fever, stomach upset. Test: blood culture as your doctor advises."],
     ["Fever rules","Test within 1–3 days, no antibiotics or painkillers on your own, plenty of water and ORS."]]},
 {id:"thal", c:"daily", t:"Thalassaemia: test before marriage", l:"Hindi", d:"2:24",
  s:"Tuesday tips, 6 Oct 2026. One blood test can protect your future child.",
  x:[["Carrier vs major","Carriers are usually healthy. Thalassaemia major needs blood transfusions every 2–4 weeks for life."],
     ["The risk","If both parents are carriers, each pregnancy has a 1 in 4 chance of thalassaemia major."],
     ["The test","CBC gives the first clue; HPLC confirms. Once in a lifetime, ideally before marriage or pregnancy."],
     ["Myth","Not all anaemia needs iron. Take iron only as your doctor advises."]]}
];

const KEYS = {
 uric:"uric acid test, uric acid normal range, high uric acid, uric acid symptoms, gout, gout test, joint pain test, big toe pain, hyperuricemia, serum uric acid, 24 hour urine uric acid, kidney stone test, uric acid in hindi, uric acid kitna hona chahiye, uric acid kaise kam kare, uric acid badhne ke lakshan, gathiya, यूरिक एसिड, यूरिक एसिड टेस्ट, यूरिक एसिड कितना होना चाहिए, गठिया, जोड़ों का दर्द, पैर के अंगूठे में दर्द, health test simplified",
 lft:"liver sgpt sgot bilirubin jaundice fatty liver hepatitis",
 lipid:"cholesterol ldl hdl triglycerides heart",
 cbc:"complete blood count haemoglobin hemoglobin hb platelets wbc rbc anaemia anemia dengue",
 kft:"kidney rft renal creatinine urea uric acid egfr",
 usg:"ultrasound sonography usg abdomen stone gallbladder",
 echo:"2d echo heart echocardiography",
 urine:"urine re routine examination",
 culture:"urine culture uti infection antibiotic",
 hba1c:"sugar diabetes glucose fasting pp hba1c",
 vitd:"vitamin d b12 bones",
 alz:"ptau217 test, ptau217 amyloid ratio, alzheimer blood test india, amyloid blood test, alzheimer test, alzheimer's disease, alzheimer test in hindi, dementia test, memory loss test, how is alzheimer diagnosed, alzheimer symptoms, early signs of dementia, memory loss in elderly, forgetfulness in old age, MMSE test, MRI brain for dementia, CT scan brain memory loss, vitamin B12 memory loss, thyroid and memory loss, alzheimer blood test, p-tau217 blood test, dementia in India, prevent dementia, brain health tips, अल्ज़ाइमर, अल्ज़ाइमर टेस्ट, डिमेंशिया, भूलने की बीमारी, याददाश्त कमजोर होना, bhoolne ki bimari, yaaddasht kamzor, health test simplified",
 sugar:"blood sugar test, fasting blood sugar, FBS test, PP sugar test, PPBS test, post meal sugar, GTT test, glucose tolerance test, OGTT 75 g, normal sugar level, diabetes test, prediabetes, sugar test in hindi, fasting sugar normal range, sugar test kaise hota hai, sugar test kab karaye, DIPSI test, gestational diabetes test, pregnancy sugar test, diabetes in India, शुगर टेस्ट, खाली पेट शुगर, डायबिटीज़ जांच, शुगर कितनी होनी चाहिए, health test simplified",
 ecg:"ECG test, ECG test in hindi, electrocardiogram, EKG test, ECG kya hai, ECG kaise hota hai, ECG report kaise samjhe, normal heart rate, chest pain test, palpitations test, heart attack symptoms, heart attack ke lakshan, irregular heartbeat, Holter test, TMT test, 2D echo, ECG before surgery, ईसीजी टेस्ट, ईसीजी क्या है, दिल की जांच, सीने में दर्द, दिल का दौरा लक्षण, dil ki jaanch, heart test in hindi, health test simplified",
 thyroid:"thyroid tsh t3 t4 hypothyroid hyperthyroid goitre weight hair fall",
 dmarker:"double marker pregnancy down syndrome nt scan",
 nipt:"nipt pregnancy dna down syndrome",
 cvs:"cvs amniocentesis pregnancy",
 karyo:"karyotype karyotyping chromosome miscarriage infertility",
 cma:"microarray cma 750k 315k chromosome autism delay",
 wes:"exome wes sequencing gene genetic",
 fever:"dengue malaria typhoid fever ns1 widal",
 thal:"thalassaemia thalassemia hplc carrier marriage"
};
